version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/petunda-fiberglass.com.crt:/etc/ssl/certs/petunda-fiberglass.com.crt:ro
      - ./certs/petunda-fiberglass.com.key:/etc/ssl/private/petunda-fiberglass.com.key:ro
    restart: always
